### ISSUE TITLE
Permitir a los no-moderadores reportar mensajes

### ISSUE THREAD

**Issue by danirod** [makigas/clank#440]
Ahora mismo sólo un mod puede utilizar el click derecho para gestionar los reportes de un mensaje. En cuanto el comando lo usa una persona que no tenga permisos de moderación, obtiene un mensaje como este:

![imagen](https://user-images.githubusercontent.com/1568690/131925470-74c40b93-11ed-4ebd-8698-73e770cd3657.png)

El propósito de este ticket es incorporar un comportamiento real cuando un no moderador activa este menú contextual.

Cambios a hacer:

- [x] Incorporar al modelo ModReport un campo para señalizar si procede de una cuenta con permisos de moderación o no (sudo mode).
- [x] Incorporar al modelo ModReport un campo para guardar una nueva propiedad llamada ALERT. Cuando se crea un evento de moderación sin modo sudo, el campo ALERT permite a un no-moderador indicar quién puede ver el mensaje. Existen tres grupos de visibilidad:
  * Reporte estandar: se envía al #modlog.
  * Reporte sensible: es un tipo de alerta de moderación que sólo notifica a admin.
  * Reporte comunitario: es un tipo de alerta de moderación que se manda a un canal público para que usuarios de confianza puedan votar.

- [x] Desdoblar un diálogo condicional según si el reporte es de tipo sudo o no. Los reportes de tipo sudo son como los de siempre, y permiten ejecutar una acción de moderación real. Los reportes que no son de tipo sudo sólo pueden proponerlo para que alguien lo revise:

![imagen](https://user-images.githubusercontent.com/1568690/131925645-3d0f02e3-5198-4f76-9f49-3ae8157c7f5b.png)

- [x] Cuando el diálogo es de tipo no-sudo, el botón Enviar emplea el verbo "Informar".

![imagen](https://user-images.githubusercontent.com/1568690/131925699-6661a5d5-ff4a-40da-9c41-2b164aa91f04.png)

- [x] Agregar una interacción de tipo Select para persistir los cambios hechos al desplegable.
- [x] Crear un nuevo renderer para los ModReports. Requisitos extra:
  * Sólo moderación y administración debe poder ver la cuenta que genera un reporte de este tipo. De forma pública los reportes siempre se deben comunicar anónimamente.
  * Deben incluirse IDs para poder hacer búsquedas por ID.
  * En general la plantilla podría estar basada en el WarnEvent actual.

- [x] Implementar la lógica del botón Informar para que renderice un ModReport y lo mande al canal oportuno según el tipo de alerta (lo envía a modlog si es una alerta estandar, a modlog-sensible si es una alerta sensible...)
