### ISSUE TITLE
Canal de hilos

### ISSUE THREAD

**Issue by danirod** [makigas/clank#441]
Con los nuevos permisos de Discord para el control de hilos, es posible definir canales donde sólo se pueden crear hilos si se apaga el permiso para Enviar Mensajes pero se deja encendido el permiso para Crear Hilos. Desafortunadamente, no es del todo aparente debido a que en la interfaz web el botón (+) aparece demasiado grisáceo como para darse cuenta de que se podría abrir un hilo.

![imagen](https://user-images.githubusercontent.com/1568690/131926645-1ca947ae-7591-4cfa-9ce7-b62c1776ad8b.png)

Así que vamos a jugar un poco con el sistema para hacerlo más aparente:
* Cuando un canal se declara como "sólo hilos", se envía una tostada que avisa de esto. El contenido de la tostada dice:
  > En este canal todos los mensajes deben estar en un hilo. Utiliza el botón ➕ para crear un hilo.
* Cuando se envía una tostada a un canal "sólo hilos", el bot debe recordar el identificador de la tostada para poder eliminarla más tarde, de forma parecida a como ocurre con [tombstone](https://github.com/makigas/clank/blob/trunk/src/hooks/tombstone.ts).
* Cuando se recibe un mensaje nuevo en un canal de "sólo hilos", el bot debe eliminar la vieja tostada usando el identificador recordado previamente y publicar una tostada nueva para que siempre sea el mensaje más reciente de ese canal.

Tareas:

- [x] Diseñar la tostada.
- [ ] Preparar los cambios en la tagbag de un Servidor para recordar un hash de mensajes marker. El modelo de datos es idéntico al de la tombstone: `{ [ channel_id: Snowflake ]: Message }`.
- [ ] Crear el hook y ponerlo pendiente del messageCreate. Cuando se crea un hilo nuevo se reciben mensajes de [tipo 18](https://discord.com/developers/docs/resources/channel#message-object-message-types).

**Comment by danirod** [comment]
Descartamos idea porque Android.
